### ISSUE TITLE
Won't run after Docker Update

### ISSUE THREAD

**Issue by krash1220** [vace117/calibre-dedrm-docker-image#3]
Linux Mint 20.1
Docker 5:20.10.7~3-0~ubuntu-focal

It creates the image and container but when I try to start it I get the following error.

"Error": "OCI runtime create failed: invalid mount {Destination:] Type:bind Source:/var/lib/docker/volumes/4b53b46910529411aa4b375cbb1114c543f579d016bb34cd85804120deb713b5/_data Options:[rbind]}: mount destination ] not absolute: unknown",

**Comment by theiltho** [comment]
Hi @krash1220 do you have a solution for this issue? I'm running into the same error

**Comment by krash1220** [comment]
Yes and no. At first I just installed the previous version of docker and locked the version so it wouldn't update. But after not getting any response on here I just stopped using it. I started using DeDRM version 7.2.1 in calibre and put the serial number from my Oasis into eink kindle ebooks  in the configuration and physically download the books from Amazon and that works for me.

**Comment by theiltho** [comment]
omg that did it! Downloading the book from Amazon works perfectly, thanks man! :rocket:

**Comment by krash1220** [comment]
You are welcome. Glad I could help.
